export const days = [
  {
    day: 1, date: "Di. 16. Juni", title: "Anreise", emoji: "🚐", accent: "#4A7C6F",
    overnight: "Ansitz Gamp, Klausen", overnightUrl: "https://ansitzgamp.com/en/",
    drive: "Mietingen → Klausen · ca. 3,5–4 Std.",
    img: "https://images.unsplash.com/photo-1592966682450-e3b1c9b3b8c0?w=800&q=80",
    imgFallback: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Klausen_Chiusa_Eisacktal.jpg/1280px-Klausen_Chiusa_Eisacktal.jpg",
    mapCenter: [46.6078, 11.6553], mapZoom: 9,
    googleMapsUrl: "https://www.google.com/maps/dir/Mietingen/Klausen,+South+Tyrol,+Italy",
    appleMapsUrl: "https://maps.apple.com/?saddr=Mietingen,Germany&daddr=Chiusa,Italy",
    program: [
      { time: "16:00", text: "Abfahrt Mietingen — A7/A96 → Kempten → Füssen → Brenner → A22 → Ausfahrt Klausen" },
      { time: "20:00", text: "Ankunft Ansitz Gamp, Klausen — einchecken, Abend genießen" },
    ],
    tips: ["🎫 Österreich-Vignette vorab digital kaufen", "🛣️ Brennermaut ca. 10 €", "⚠️ Ducato-Anfahrt über Kollmann/Waidbruck — NICHT über Völs (zu eng!)"],
    fotospots: [],
  },
  {
    day: 2, date: "Mi. 17. Juni", title: "Villnösstal", emoji: "⛪", accent: "#5E8A6E",
    overnight: "Ansitz Gamp, Klausen", overnightUrl: "https://ansitzgamp.com/en/",
    drive: "Klausen → Villnösstal · ca. 15 Min.",
    img: "https://images.unsplash.com/photo-1601370690183-1c7796ecec61?w=800&q=80",
    imgFallback: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Ranui_church_2.jpg/1280px-Ranui_church_2.jpg",
    mapCenter: [46.640, 11.720], mapZoom: 12,
    googleMapsUrl: "https://www.google.com/maps/dir/Chiusa,Italy/St+Johann+in+Ranui,+Italy/Santa+Maddalena,+Funes,+Italy",
    appleMapsUrl: "https://maps.apple.com/?saddr=Chiusa,Italy&daddr=Ranui+Chapel,+Funes,+Italy",
    program: [
      { time: "09:00", text: "Fahrt ins Villnösstal (nur 15 Min. ab Klausen!)" },
      { time: "10:00", text: "St. Johann Kirche in Ranui — ikonisches Südtirol-Postkartenmotiv" },
      { time: "11:00", text: "St. Magdalena — Panoramaweg zur Bank mit traumhaftem Ausblick" },
      { time: "13:00", text: "Adolf-Munkel-Weg: leichte Wanderung unter den Geislerspitzen (2–3 Std.)" },
      { time: "18:00", text: "Rückfahrt nach Klausen, Abendessen" },
    ],
    tips: ["🅿️ Parkplatz Zanser Alm: ca. 25 € Wohnmobil/Tag", "⏰ Mittags Parkplätze voll — früh starten!"],
    fotospots: ["📸 St. Johann Kirche — bestes Licht morgens", "📸 St. Magdalena Panoramabank — Abendlicht"],
  },
  {
    day: 3, date: "Do. 18. Juni", title: "Grödnerjoch · Alta Badia · Misurina", emoji: "🏔️", accent: "#6B7FA3",
    overnight: "Area Sosta Camper, Misurina", overnightUrl: "https://park4night.com/en/place/14500",
    drive: "Klausen → Misurina · ca. 3 Std. mit Stopps 6–7 Std.",
    img: "https://images.unsplash.com/photo-1605540436563-5bca919ae766?w=800&q=80",
    imgFallback: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Gardena_Pass_2.jpg/1280px-Gardena_Pass_2.jpg",
    mapCenter: [46.57, 11.98], mapZoom: 10,
    googleMapsUrl: "https://www.google.com/maps/dir/Chiusa,Italy/Passo+Gardena,Italy/Alta+Badia,Italy/Misurina,Italy",
    appleMapsUrl: "https://maps.apple.com/?saddr=Chiusa,Italy&daddr=Misurina,Italy",
    program: [
      { time: "09:00", text: "Abfahrt über Grödnerjoch (2.121 m) — Fotostopp, Sella- und Cir-Gruppe" },
      { time: "11:00", text: "Alta Badia — Stern/La Villa: ladinische Küche, Mittagsstopp" },
      { time: "14:00", text: "Weiterfahrt Richtung Misurina über Falzarego- und Valparola-Pass" },
      { time: "16:30", text: "Ankunft Misurinasee — Area Sosta (58 Stellplätze, First Come First Served)" },
      { time: "17:30", text: "Spaziergang am Misurinasee, früh schlafen!" },
    ],
    tips: ["🅿️ Area Sosta: kein Reservierungssystem — früh ankommen!", "⏰ Morgen Abfahrt 06:30 Uhr zu den Drei Zinnen"],
    fotospots: ["📸 Grödnerjoch — Sella-Gruppe Panorama", "📸 Misurinasee Abendstimmung"],
  },
  {
    day: 4, date: "Fr. 19. Juni", title: "Drei Zinnen · Cadini di Misurina", emoji: "🗻", accent: "#7B6B9A",
    overnight: "Camping Olympia, Toblach", overnightUrl: "https://www.camping-olympia.com",
    drive: "Misurina → Drei Zinnen 10 Min. · → Toblach 20 Min.",
    img: "https://images.unsplash.com/photo-1583309217394-d2e8b8c0c8c8?w=800&q=80",
    imgFallback: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Cadini_di_Misurina.jpg/1280px-Cadini_di_Misurina.jpg",
    mapCenter: [46.630, 12.270], mapZoom: 12,
    googleMapsUrl: "https://www.google.com/maps/dir/Misurina,Italy/Rifugio+Auronzo,Italy/Dobbiaco,Italy",
    appleMapsUrl: "https://maps.apple.com/?saddr=Misurina,Italy&daddr=Rifugio+Auronzo,Italy",
    program: [
      { time: "06:30", text: "Abfahrt zur Mautstation (nur 10 Min. ab Misurina)" },
      { time: "06:45", text: "Mautstation: 45 € / 12 Std. — Ticket aufheben!" },
      { time: "07:00", text: "📸 Cadini di Misurina — Wanderweg #117, 1 Std. Hin/zurück. Bestes Morgenlicht!" },
      { time: "09:00", text: "Rundweg Drei Zinnen (ca. 10 km, 4 Std., leicht–mittel)" },
      { time: "13:30", text: "Mittagspause Auronzo-Hütte, dann runter nach Toblach" },
      { time: "15:30", text: "Einchecken Camping Olympia, entspannter Abend" },
    ],
    tips: ["⏰ Zeitfenster VORAB reservieren → auronzo.info", "🧥 Morgens nur 7° auf 2.300m — warm anziehen!", "😴 Früh ins Bett — morgen Pragser Wildsee!"],
    fotospots: ["📸 Cadini di Misurina — Sonnenaufgangslicht", "📸 Drei Zinnen Nordansicht"],
  },
  {
    day: 5, date: "Sa. 20. Juni", title: "Pragser Wildsee · Seiser Alm · Shooting", emoji: "📷", accent: "#A06B5A",
    overnight: "Ansitz Gamp, Klausen", overnightUrl: "https://ansitzgamp.com/en/",
    drive: "Toblach → Pragser Wildsee 15 Min. → Klausen 1 Std.",
    img: "https://images.unsplash.com/photo-1583774248831-c5b4c8e7c5c5?w=800&q=80",
    imgFallback: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Lago_di_Braies.jpg/1280px-Lago_di_Braies.jpg",
    mapCenter: [46.640, 11.900], mapZoom: 10,
    googleMapsUrl: "https://www.google.com/maps/dir/Dobbiaco,Italy/Lago+di+Braies,Italy/Chiusa,Italy",
    appleMapsUrl: "https://maps.apple.com/?saddr=Dobbiaco,Italy&daddr=Lago+di+Braies,Italy",
    program: [
      { time: "07:00", text: "Abfahrt → Pragser Wildsee (15 Min.) — VOR dem Ansturm!" },
      { time: "07:30", text: "Pragser Wildsee — Seeumrundung 3,8 km im Morgenlicht" },
      { time: "10:30", text: "Abfahrt Richtung Klausen/Gröden (ca. 1 Std.)" },
      { time: "12:00", text: "Ansitz Gamp — Mittagspause, Outfit vorbereiten 💇" },
      { time: "17:00", text: "Aufstieg Baita Seurasas vom Parkplatz Cristauta-Praplan (45 Min.)" },
      { time: "18:00", text: "📷 Fotoshooting — Almwiesen, Langkofel & Sellagruppe" },
      { time: "21:00", text: "Sonnenuntergang / Enrosadira (Alpenglühen)" },
    ],
    tips: ["🅿️ Pragser Wildsee P1: 45 € inkl. 20 € Verzehr → pragsparking.com", "🚐 Seiser Alm Zufahrt 9–17 Uhr gesperrt → Seilbahn", "🌄 Sonnenuntergang ca. 21:08 Uhr"],
    fotospots: ["📸 Pragser Wildsee — bestes Licht morgens", "📸 Baita Seurasas — Almwiesen & Langkofel", "📸 Enrosadira zum Sonnenuntergang"],
  },
  {
    day: 6, date: "So. 21. Juni", title: "Shooting Seceda · Heimfahrt", emoji: "🌅", accent: "#8A6A4A",
    overnight: "Heimfahrt nach Mietingen", overnightUrl: null,
    drive: "Klausen → Mietingen · ca. 3,5–4 Std.",
    img: "https://images.unsplash.com/photo-1609860085000-1c8e9c8e9c8e?w=800&q=80",
    imgFallback: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Seceda_-_panoramio.jpg/1280px-Seceda_-_panoramio.jpg",
    mapCenter: [46.578, 11.688], mapZoom: 12,
    googleMapsUrl: "https://www.google.com/maps/dir/Ortisei,Italy/Seceda,Italy/Chiusa,Italy/Mietingen,Germany",
    appleMapsUrl: "https://maps.apple.com/?saddr=Ortisei,Italy&daddr=Mietingen,Germany",
    program: [
      { time: "06:00", text: "Aufstieg Seceda — zu Fuß (2 Std.) ODER Seilbahn ab 07:30 Uhr" },
      { time: "07:30", text: "📷 Shooting Seceda-Kamm — Sonnenaufgang, Geislerspitzen orange" },
      { time: "09:00", text: "Mittagslicht-Shooting — Candid im Gegenlicht auf dem Kamm" },
      { time: "11:00", text: "Seilbahn runter, einpacken, letzter Kaffee" },
      { time: "12:00", text: "⚠️ Späteste Abfahrt! Klausen → Brenner → Mietingen" },
      { time: "15:30", text: "🏠 Ankunft Mietingen" },
    ],
    tips: ["⏰ Spätestens 12:00 Uhr abfahren!", "🌄 Sonnenaufgang Mitte Juni ca. 05:18 Uhr", "🧥 Morgens 5° — warme Schicht mitnehmen!"],
    fotospots: ["📸 Seceda-Kamm — Sonnenaufgang & Geislerspitzen", "📸 Candid im Gegenlicht", "📸 Blick ins Grödnertal"],
  },
];

export const checklist = [
  { item: "Ansitz Gamp buchen (4 Nächte: 16., 17., 20., 21.)", url: "https://ansitzgamp.com/en/" },
  { item: "Camping Olympia, Toblach buchen (19.)", url: "https://www.camping-olympia.com" },
  { item: "Area Sosta Misurina — früh ankommen (18.)", url: "https://park4night.com/en/place/14500" },
  { item: "Drei Zinnen Zeitfenster reservieren", url: "https://auronzo.info/en/parking-tre-cime-di-lavaredo/" },
  { item: "Pragser Wildsee Parkticket buchen", url: "https://www.pragsparking.com/en" },
  { item: "Österreich-Vignette kaufen", url: "https://digitale-vignette-online.at/de/routenplaner" },
  { item: "Fotografin bestätigen & Spots schicken", url: null },
];
